CREATE TABLE IF NOT EXISTS entry (
	id SERIAL NOT NULL,
	type CHAR NOT NULL,
	datetime TIMESTAMP NOT NULL DEFAULT NOW(),
	title TEXT NOT NULL,
	lang  TEXT NULL DEFAULT NULL,
	text TEXT NOT NULL,
	link TEXT NULL DEFAULT NULL,
	git TEXT NULL DEFAULT NULL,
	PRIMARY KEY ("id")
);